
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvtnppyzuqkdayumcwph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dG5wcHl6dXFrZGF5dW1jd3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTI3MTksImV4cCI6MjA1NzE4ODcxOX0.-P68z3094bNaluYCPCSHmHM5gUmx-pjHqaCF5arlvAY";

// Configure with offline support
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: globalThis.localStorage
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  supabaseOptions
);
